
// types/Service.ts
export interface Service {
  id: number;
  name: string;
  description: string;
  qty: number;
  qty_note: Record<string, any>;
  duration: number;
  duration_original: number;
  duration_note: Record<string, any>;
  unit_price: number;
  pricing_model: string;
  discount?: number; // Optional if some services might not have a discount
}

// data/DataService.ts
export const services: Record<string, Service> = {
  android: {
    id: 1,
    name: 'Campagne publicitaire Android',
    description: 'Optimisez vos publicités sur les applications Android.',
    qty: 50000,
    qty_note: { status: 'active', '0': '0', '5': '1', '10': '1.5', '30': '2' },
    duration: 30,
    duration_original: 30,
    duration_note: { status: 'active', '0': '0', '5': '1.8', '10': '1.5', '20': '1.2', '30': '1' },
    unit_price: 3.0,
    pricing_model: 'impressions',
  },
  internet: {
    id: 2,
    name: 'Campagne publicitaire Web',
    description: 'Diffusez vos publicités sur le web pour toucher un large public.',
    qty: 70000,
    qty_note: { status: 'active', '0': '0', '5': '1', '10': '1.5', '30': '2' },
    duration: 30,
    duration_original: 30,
    duration_note: { status: 'active', '0': '0', '5': '1.8', '10': '1.5', '20': '1.2', '30': '1' },
    unit_price: 2.5,
    pricing_model: 'impressions',
  },
  youtube: {
    id: 3,
    name: 'Campagne publicitaire YouTube',
    description: 'Boostez votre visibilité avec des publicités vidéo sur YouTube.',
    qty: 100000,
    qty_note: { status: 'active', '0': '0', '5': '1', '10': '1.5', '30': '2' },
    duration: 30,
    duration_original: 30,
    duration_note: { status: 'active', '0': '0', '5': '1.8', '10': '1.5', '20': '1.2', '30': '1' },
    unit_price: 4.0,
    pricing_model: 'impressions',
  },
  facebook: {
    id: 4,
    name: 'Campagne publicitaire Facebook',
    description: 'Optimisez vos publicités avec des campagnes ciblées.',
    qty: 40000,
    qty_note: { status: 'active', '0': '0', '5': '1', '10': '1', '30': '1' },
    duration: 30,
    duration_original: 30,
    duration_note: { status: 'active', '0': '0', '5': '1.8', '10': '1.5', '20': '1.2', '30': '1' },
    unit_price: 2.5,
    pricing_model: 'impressions',
  },
  instagram: {
    id: 6,
    name: 'Campagne publicitaire Instagram',
    description: 'Boostez votre visibilité sur Instagram.',
    qty: 30000,
    qty_note: { status: 'active', '0': '0', '5': '1', '10': '1', '30': '1' },
    duration: 30,
    duration_original: 30,
    duration_note: { status: 'active', '0': '0', '5': '1.8', '10': '1.5', '20': '1.2', '30': '1' },
    unit_price: 3.0,
    pricing_model: 'impressions',
  },
  whatsapp: {
    id: 7,
    name: 'Campagne publicitaire WhatsApp',
    description: 'Engagez vos clients sur WhatsApp.',
    qty: 20000,
    qty_note: { status: 'active', '0': '0', '5': '1', '10': '1', '30': '1' },
    duration: 30,
    duration_original: 30,
    duration_note: { status: 'active', '0': '0', '5': '1.8', '10': '1.5', '20': '1.2', '30': '1' },
    unit_price: 2.0,
    pricing_model: 'impressions',
  },
  linkedin: {
    id: 8,
    name: 'Campagne publicitaire LinkedIn',
    description: 'Touchez les professionnels sur LinkedIn.',
    qty: 15000,
    qty_note: { status: 'active', '0': '0', '5': '1', '10': '1', '30': '1' },
    duration: 30,
    duration_original: 30,
    duration_note: { status: 'active', '0': '0', '5': '1.8', '10': '1.5', '20': '1.2', '30': '1' },
    unit_price: 4.0,
    pricing_model: 'impressions',
  },
  tiktok: {
    id: 9,
    name: 'Campagne publicitaire TikTok',
    description: 'Captez l\’attention des jeunes sur TikTok.',
    qty: 25000,
    qty_note: { status: 'active', '0': '0', '5': '1', '10': '1', '30': '1' },
    duration: 30,
    duration_original: 30,
    duration_note: { status: 'active', '0': '0', '5': '1.8', '10': '1.5', '20': '1.2', '30': '1' },
    unit_price: 2.8,
    pricing_model: 'impressions',
  },
  snapchat: {
    id: 10,
    name: 'Campagne publicitaire Snapchat',
    description: 'Diffusez vos publicités sur Snapchat.',
    qty: 20000,
    qty_note: { status: 'active', '0': '0', '5': '1', '10': '1', '30': '1' },
    duration: 30,
    duration_original: 30,
    duration_note: { status: 'active', '0': '0', '5': '1.8', '10': '1.5', '20': '1.2', '30': '1' },
    unit_price: 2.2,
    pricing_model: 'impressions',
  },
  conception_image: {
    id: 11,
    name: 'Conception d\'image',
    description: 'Des images qui renforcent votre marque. (Par campagne)',
    qty: 10,
    qty_note: { status: 'active', '0': '0', '5': '1', '10': '1.5', '30': '2' },
    duration: 8,
    duration_original: 5,
    duration_note: { status: 'disable', '0': '0', '5': '1.5', '10': '2', '30': '3' },
    unit_price: 5000,
    pricing_model: 'images',
    discount: 0.3,
  },
  conception_video: {
    id: 12,
    name: 'Conception vidéo',
    description: 'Des vidéos engageantes pour capter l\'attention de votre audience. (Par vidéo)',
    qty: 1,
    qty_note: { status: 'active', '0': '0', '2': '1.2', '5': '1.5', '10': '2' },
    duration: 5,
    duration_original: 5,
    duration_note: { status: 'disable', '0': '0', '5': '1.5', '10': '2', '30': '3' },
    unit_price: 45000,
    pricing_model: 'video',
  },
  automatisation_publications: {
    id: 13,
    name: 'Automatisation des publications',
    description: 'Automatisez pour une communication ponctuelle.',
    qty: 1,
    qty_note: { status: 'active', '0': '0' },
    duration: 2,
    duration_original: 2,
    duration_note: { status: 'disable' },
    unit_price: 20000,
    pricing_model: 'campagne',
  },
  rapport_campagne: {
    id: 14,
    name: 'Rapport de la Campagne',
    description: 'Rapports de campagne pour affiner vos stratégies.',
    qty: 1,
    qty_note: { status: 'active', '0': '0' },
    duration: 2,
    duration_original: 2,
    duration_note: { status: 'disable' },
    unit_price: 10000,
    pricing_model: 'rapport',
  },
};